### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by tooolbox** [apvanlaan/laravel-usaepay#8]
From what I can tell, this uses the [USAePay REST API](https://help.usaepay.info/developer/rest-api/), but you somehow have many more fields than are documented on their website.

I'm trying, out of necessity, to write a library in another language, and having a hard-as-heck time finding all the fields or seeing how things link together.

Hence:

- How did you gain your secret insider arcane knowledge of this API?
- Are you confident in the accuracy of your information?
- Can you illuminate the path of a neophyte such as myself?

Or perhaps, more specifically:

1. You can apparently pass `save_card` to persist a token, but their example response doesn't have a token in it...?
2. Their site has an example of how to use a one-time browser-tokenized card when performing a sale, but not a permanent token...?
3. Apparently you can *receive* [line items](https://help.usaepay.info/developer/rest-api/more/commonobjects/#lineitems) but I would hope I could send them too when I do a sale?  This is a typical feature for a gateway, but I don't see that on their request object.

I will likely browse your source code to see what I can learn, but figured I would reach out as well.  Thanks.

**Comment by apvanlaan** [comment]
@tooolbox Hey sorry for the delay in seeing your questions.  Seeing as you closed this yourself did you find the answers you were looking for, or is there something I can still help with? 

-Aaron

**Comment by tooolbox** [comment]
Hey @apvanlaan thanks, yeah I did get some answers so I didn't want to bother you further 😉 

Wow, that link is very helpful though, those docs are very nice in comparison.  Wild that I wasn't able to find them earlier.  Thanks!
